server:
  port: 9999
  contextPath: /uaa

#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka/

security:
  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG

# Datasource and JPA configuration to be used for storing the OAuth authorization details
# and token store
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/auth
    username: root
    password: flatland
    driver-class: com.mysql.jdbc.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none



